<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\InvoiceProcessor.Domain\InvoiceProcessor.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
    </ItemGroup>

</Project>
